### ISSUE TITLE
Stay in Zalo app and not comeback main app.

### ISSUE THREAD

**Issue by ducpt2** [maitrungduc1410/react-native-zalo-kit#1]
Thank you for your library, but i can not login. When i call login function, it stay in Zalo app and not comback to my app. So i can not login success.
May you take a look? Thanks.

**Comment by ducpt2** [comment]
I add more infomation for this issue.
Inside Zalo developer page, in ios page, how can i fill all the infomation please?
- BundleID
- iTunesID
- TeamID
- Key Identifier
- Private Key 
Thanks.

**Comment by maitrungduc1410** [comment]
> I add more infomation for this issue.
> Inside Zalo developer page, in ios page, how can i fill all the infomation please?
> 
> * BundleID
> * iTunesID
> * TeamID
> * Key Identifier
> * Private Key
>   Thanks.

It's in your project, not in Zalo developer portal:
- For iOS: you need Bundle ID, which you can find on Xcode -> Select your project target
- For Android: you need your project's package name + Application Hash Key. For getting Application Hash Key, there's a helper function, please check the docs.

The rest in your comment is not used for setting up with Zalo

**Comment by maitrungduc1410** [comment]
> Thank you for your library, but i can not login. When i call login function, it stay in Zalo app and not comback to my app. So i can not login success.
> May you take a look? Thanks.

Please check if you have this things set up correctly:
- Successfully register your project on Zalo developer portal with iOS and Android instructions as I mentioned in my comment above. This step is **important**
- If you haven't turned your app to Live, you have to add your Zalo account as your project's developer, I **recommend** you turn it to Live to get all functionalities
- Try parsing `AUTH_VIA_WEB` when `login`, because sometimes the Zalo API doesn't work nicely and login via App may not work

**Comment by ducpt2** [comment]
Thank you a lot. Have a nice day.

**Comment by maitrungduc1410** [comment]
I tested my library once again and everything was working fine. You just to make sure to follow my instructions :)
